env:                                
  contexts:                           
    - name: ZapContext                  
      urls: 
        - http://localhost:3001                   
      includePaths:
        - "/statistics"
        - "/homepage"
      excludePaths:
        - "/register"
        - "/login"                                   
      authentication:
        method: json                      
        parameters:                                                     
          loginRequestUrl: "http://localhost:3000/auth/login"            
          loginRequestBody: '{"username":"${username}", "password":"${password}"}'
          loginPageUrl: "http://localhost:3001/login"          
        verification:
          method: response                    
          loggedInRegex: '"message":\\s*"Logged in succesfully"'            
          loggedOutRegex: '"message":\\s*"Logged out succesfully"'                                 
      sessionManagement:
        method: cookie                                    
      technology:                     
        include: [JavaScript]                     
      users:                        
      - name: zapUser                         
        credentials:                 
          username: "zapuser"                  
          password: "Hashedpassword1!"                   
  vars:                             
    username: "zapuser"      
    password: "Hashedpassword1!"     
  parameters:
    failOnError: true                       
    failOnWarning: false             
    continueOnFailure: false          
    progressToStdout: true       

jobs:
  - type: spiderAjax
    parameters:
      context: "ZapContext"                     
      maxDuration: 10                     
      maxCrawlDepth: 7                
      numberOfBrowsers: 1                
      runOnlyIfModern: false           
      inScopeOnly: true              
      browserId: "firefox-headless"     
      clickDefaultElems: true          
      clickElemsOnce: true              
      eventWait: 2000                               
      randomInputs: true               
      reloadWait: 5000
      elements:
      - "button"
      - "input"
      - "a"
      - "li"
      - "div"                    
      excludedElements:                
        - description: "Logout Button"
          element: "button"
          text: "Logout"

    tests:
      - name: 'URLS Found'          
        type: 'stats'
        statistic: 'spiderAjax.urls.added'
        operator: '>='
        value: 1
        onFail: 'info'

      - name: 'Verify Login Successful'
        type: 'stats'
        statistic: 'stats.auth.success'
        operator: '>='
        value: 1
        onFail: 'info'
      
      - name: 'Session Token Detected in Cookies'
        type: 'stats'
        statistic: 'stats.auth.sessiontoken.access_token' 
        operator: '>='
        value: 1
        onFail: 'warn'

      - name: 'No Logged Out States'
        type: 'stats'
        statistic: 'stats.auth.state.loggedout'
        operator: '=='
        value: 0
        onFail: 'warn'
        
  - type: activeScan                 
    parameters:
      policy: "Default Policy"                                        
      maxRuleDurationInMins: 5         
      maxScanDurationInMins: 30
  - type: report                     
    parameters:
      template: modern
      reportDir: "/zap/wrk"                                         
      reportFile: "ZAP_DAST_SCAN"                    
      reportTitle: "DAST SCAN"                    
      reportDescription: "DAST SCAN DESC"           
      displayReport: true
                     

       