env:                                
  contexts:                           
    - name: ZapContext                  
      urls: 
        - http://localhost:3001                   
      includePaths:
        - "/homepage"
        - "/statistics"
      excludePaths:
        - "/register"                                    
      authentication:
        method: json                      
        parameters:                                                     
          loginRequestUrl: "http://localhost:3000/auth/login"            
          loginRequestBody: '{"username":"${username}", "password":"${password}"}'
          loginPageUrl: "http://localhost:3001/login"          
        verification:
          method: response                    
          loggedInRegex: '"message":\\s*"Logged in succesfully"'            
          loggedOutRegex: '"message":\\s*"Logged out succesfully"'                                 
      sessionManagement:
        method: cookie                                    
      technology:                     
        include: [JavaScript]                     
      users:                        
      - name: zapUser                         
        credentials:                 
          username: "zapuser"                  
          password: "Hashedpassword1!"                   
  vars:                             
    username: "zapuser"      
    password: "Hashedpassword1!"     
  parameters:
    failOnError: true                       
    failOnWarning: false             
    continueOnFailure: false          
    progressToStdout: true       

jobs:
  - type: spiderAjax
    parameters:
      context: "ZapContext"                # Nazwa kontekstu, który chcesz spiderować
      user: ""                             # Opcjonalny użytkownik, jeśli wymagane jest uwierzytelnienie
      url: "http://localhost:3001/homepage"         # Adres URL, od którego zaczyna się spidering
      maxDuration: 10                      # Maksymalny czas trwania spideringu w minutach
      maxCrawlDepth: 5                     # Maksymalna głębokość crawlowania
      numberOfBrowsers: 1                  # Liczba przeglądarek do użycia
      runOnlyIfModern: false               # Czy uruchamiać tylko dla "nowoczesnych aplikacji"
      inScopeOnly: true                    # Ignorowanie URLi poza zakresem kontekstu
      browserId: "firefox-headless"        # Przeglądarka do użycia
      clickDefaultElems: true              # Klikanie tylko domyślnych elementów
      clickElemsOnce: true                 # Klikanie każdego elementu tylko raz
      eventWait: 1000                      # Czas oczekiwania po zdarzeniu (ms)
      maxCrawlStates: 100                  # Maksymalna liczba stanów crawlowania
      randomInputs: true                   # Wprowadzanie losowych danych do inputów
      reloadWait: 1000                     # Czas oczekiwania po załadowaniu strony (ms)
      excludedElements:                    # Lista elementów do wykluczenia
        - description: "Logout Button"
          element: "button"
          attributeName: "aria-label"
          attributeValue: "Logout"

    tests:
      - name: 'At least 100 URLs found'           # Test, aby upewnić się, że znaleziono odpowiednią liczbę URLi
        type: 'stats'
        statistic: 'spiderAjax.urls.added'
        operator: '>='
        value: 1
        onFail: 'info'
  - type: activeScan                 
    parameters:
      policy: "Default Policy"                                        
      maxRuleDurationInMins: 5         
      maxScanDurationInMins: 30
  - type: report                     
    parameters:
      template: modern
      reportDir: "/zap/wrk"                                         
      reportFile: "ZAP_DAST_SCAN"                    
      reportTitle: "DAST SCAN"                    
      reportDescription: "DAST SCAN DESC"           
      displayReport: true
                     

       