env:                                
  contexts:                           
    - name: ZapContext                  
      urls: 
        - https://example.com                    
      # includePaths:
      #   - "/homepage"
      #   - "/statistics"                                    
      # authentication:
      #   method: json                      
      #   parameters:                                                     
      #     loginRequestUrl: "http://localhost:3000/auth/login"            
      #     loginRequestBody: '{"username":"${username}", "password":"${password}"}'
      #     # loginPageUrl: "http://localhost:3001/login"          
      #   verification:
      #     method: response                    
      #     loggedInRegex: '"message":\\s*"Logged in succesfully"'            
      #     loggedOutRegex: '"message":\\s*"Logged out succesfully"'                                 
      # sessionManagement:
      #   method: cookie                                    
      # technology:                     
      #   include: [JavaScript]                     
  #     users:                        
  #     - name: zapUser                         
  #       credentials:                 
  #         username: "zapuser"                  
  #         password: "Hashedpassword1!"                   
  # vars:                             
  #   username: "zapuser"      
  #   password: "Hashedpassword1!"     
  parameters:
    failOnError: true                       
    failOnWarning: false             
    continueOnFailure: false          
    progressToStdout: true       

jobs:
  - type: addOns                       # Add-on management
    parameters:
      updateAddOns: true               # Update any add-ons that have new versions
    install:                           # A list of non standard add-ons to install from the ZAP Marketplace
    - ascanrules
    - ascanrulesAlpha
    - ascanrulesBeta
    - pscanrulesBeta
    - pscanrulesAlpha
    - automation
    - domxss
    - graphql
    - openapi
    - reflect
    - reports
    - soap
    - spiderAjax
  - type: activeScan                 
    parameters:
      policy: "Default Policy"                                        
      maxRuleDurationInMins: 5         
      maxScanDurationInMins: 30
  - type: report                     
    parameters:                                         
      reportFile: "ZAP_DAST_SCAN"                    
      reportTitle: "DAST SCAN"                    
      reportDescription: "DAST SCAN DESC"           
      displayReport: true                

       