env:                                
  contexts:                           
    - name: ZapContext                  
      urls: 
        - http://localhost:3001/homepage
        - http://localhost:3001/statistics                    
      # includePaths:
      #   - "/homepage"
      #   - "/statistics"
      # excludePaths:
      #   - "/register"                                    
      authentication:
        method: json                      
        parameters:                                                     
          loginRequestUrl: "http://localhost:3000/auth/login"            
          loginRequestBody: '{"username":"${username}", "password":"${password}"}'
          loginPageUrl: "http://localhost:3001/login"          
        verification:
          method: response                    
          loggedInRegex: '"message":\\s*"Logged in succesfully"'            
          loggedOutRegex: '"message":\\s*"Logged out succesfully"'                                 
      sessionManagement:
        method: cookie                                    
      technology:                     
        include: [JavaScript]                     
      users:                        
      - name: zapUser                         
        credentials:                 
          username: "zapuser"                  
          password: "Hashedpassword1!"                   
  vars:                             
    username: "zapuser"      
    password: "Hashedpassword1!"     
  parameters:
    failOnError: true                       
    failOnWarning: false             
    continueOnFailure: false          
    progressToStdout: true       

jobs:
  - type: spiderAjax
    parameters:
      context: "ZapContext"              
      #url: "http://localhost:3001/homepage"         
      maxDuration: 10                     
      maxCrawlDepth: 5                
      numberOfBrowsers: 1                
      runOnlyIfModern: false           
      inScopeOnly: true              
      browserId: "firefox-headless"     
      clickDefaultElems: true          
      clickElemsOnce: true              
      eventWait: 1000                
      maxCrawlStates: 100                
      randomInputs: true               
      reloadWait: 1000
      elements:
      - "button"
      - "input"
      - "a"
      - "li"
      - "div"                    
      excludedElements:                
        - description: "Logout Button"
          element: "button"
          text: "Logout"

    tests:
      - name: 'URLS Found'          
        type: 'stats'
        statistic: 'spiderAjax.urls.added'
        operator: '>='
        value: 1
        onFail: 'info'
  - type: activeScan                 
    parameters:
      policy: "Default Policy"                                        
      maxRuleDurationInMins: 5         
      maxScanDurationInMins: 30
  - type: report                     
    parameters:
      template: modern
      reportDir: "/zap/wrk"                                         
      reportFile: "ZAP_DAST_SCAN"                    
      reportTitle: "DAST SCAN"                    
      reportDescription: "DAST SCAN DESC"           
      displayReport: true
                     

       