env:                                
  contexts:                           
    - name: ZapContext                  
      urls:     
        - "http://localhost:3001"                    
      includePaths:
        - "/homepage/"
        - "/statistics/"                                    
      authentication:
        method: form                      
        parameters:                
          hostname: "localhost"                   
          port: 3001                        
          loginPageUrl: "http://localhost:3001/login"               
          loginRequestUrl: "http://localhost:3000/auth/login"            
          loginRequestBody: '{"username":"${username}", "password":"${password}"}'         
        verification:
          method: response                    
          loggedInRegex: '"message":\\s*"Logged in succesfully"'            
          loggedOutRegex: '"message":\\s*"Logged out succesfully"'                                 
      sessionManagement:
        method: cookie                                    
      technology:
        exclude:                      
        include: [JavaScript]                     
      users:                        
      - name: zapUser                         
        credentials:                 
          username: "zapuser"                  
          password: "Hashedpassword1!"                   
  vars:                             
    username: "zapuser"      
    password: "Hashedpassword1!"     
  parameters:
    failOnError: true                       
    failOnWarning: false             
    continueOnFailure: false          
    progressToStdout: true
    logLevel: DEBUG          

jobs:
- type: activeScan                 
  parameters:
    context: "ZapContext"                       
    policy: "Default Policy"                    
    maxRuleDurationInMins: 5         
    maxScanDurationInMins: 30
- type: report                     
  parameters:
    template: "traditional-html"                       
    reportDir: "/zap/wrk/"                     
    reportFile: "ZAP_DAST_SCAN"                    
    reportTitle: "DAST SCAN"                    
    reportDescription: "DAST SCAN DESC"           
    displayReport: true                
  risks:                          
    - high
    - medium
    - low
    - info
  confidences:                     
    - high
    - medium
    - low
    - falsepositive
  sections:
    - all                      
  sites:
    - all           