name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.2.0'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Install dependencies (Frontend)
        working-directory: ./apps/frontend
        run: pnpm install

      - name: Install dependencies (Backend)
        working-directory: ./apps/backend
        run: pnpm install

      - name: Run linter (Frontend)
        working-directory: ./apps/frontend
        run: pnpm run lint

      - name: Run linter (Backend)
        working-directory: ./apps/backend
        run: pnpm run lint

      - name: Run TypeScript check (Frontend)
        working-directory: ./apps/frontend
        run: pnpm exec tsc --noEmit

      - name: Run TypeScript check (Backend)
        working-directory: ./apps/backend
        run: pnpm exec tsc --noEmit

      - name: Build Next.js app
        working-directory: ./apps/frontend
        run: pnpm run build

      - name: Build NestJS app
        working-directory: ./apps/backend
        run: pnpm run build

      # - name: Deploy Frontend to Vercel
      #   working-directory: ./apps/frontend
      #   run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
      
      # - name: Heroku Login
      #   run: |
      #     echo "machine api.heroku.com" >> ~/.netrc
      #     echo "  login ${{ secrets.HEROKU_EMAIL }}" >> ~/.netrc
      #     echo "  password ${{ secrets.HEROKU_API_KEY }}" >> ~/.netrc

      # - name: Deploy Backend to Heroku
      #   run: heroku git:remote -a your-heroku-app && git push heroku master

      # # Optional: Run tests after building
      # - name: Run tests (Frontend)
      #   working-directory: ./apps/frontend
      #   run: pnpm test

      # - name: Run tests (Backend)
      #   working-directory: ./apps/backend
      #   run: pnpm test
