name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.2.0'

      - name: Install dependencies (Frontend)
        working-directory: ./apps/frontend
        run: pnpm install

      - name: Install dependencies (Backend)
        working-directory: ./apps/backend
        run: pnpm install

      - name: Run linter (Frontend)
        working-directory: ./apps/frontend
        run: pnpm run lint

      - name: Run linter (Backend)
        working-directory: ./apps/backend
        run: pnpm run lint

      - name: Run TypeScript check (Frontend)
        working-directory: ./apps/frontend
        run: pnpm run tsc --noEmit

      - name: Run TypeScript check (Backend)
        working-directory: ./apps/backend
        run: pnpm run tsc --noEmit

      - name: Build Next.js app
        working-directory: ./apps/frontend
        run: pnpm run build

      - name: Build NestJS app
        working-directory: ./apps/backend
        run: pnpm run build

      # # Optional: Run tests after building
      # - name: Run tests (Frontend)
      #   working-directory: ./apps/frontend
      #   run: pnpm test

      # - name: Run tests (Backend)
      #   working-directory: ./apps/backend
      #   run: pnpm test
